[package]
name = "cpupainter"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.36.1"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_SystemInformation"
]